[package]
name = "pac194x"
version = "0.1.0"
edition = "2021"

[dependencies]
embedded-hal = "0.2"
paste = "1.0"

[dependencies.packed_struct]
version = "0.10"
default-features = false

[dependencies.register_derive]
path = "../register_derive"

[dev-dependencies]
embedded-hal-mock =  "0.8"

